# openapiのversion指定
openapi: "3.0.3"

# apiのメタ情報を記述
info:
  title: "Sample API"  #apiのタイトル
  version: "1.0.0"  #apiドキュメントのversion

# apiを提供しているサーバーを設定
servers:
- url: "http://localhost:3000"
  description: "ローカル環境"
- url: "http://sample.com"
  description: "本番環境"
paths:
  "/api/v1/hello":
    get:
      summary: "hello"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "hello"
